version: "3"
services:

  angular:
      container_name: angular
      image: oursgroumy/lcv-angular
      restart: always
      ports:
        - "80:3000"
        - "443:443"
      volumes:
      - certbot-webroot-le-cerf-vert:/app/server/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  events:
    container_name: events
    image: oursgroumy/lcv-events
    restart: always
    ports:
      - "3001:3001"
    
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

  certbot:
    image: oursgroumy/lcv-ssl-certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-le-cerf-vert:/webroots/le-cerf-vert.ovh/.well-known
      - certbot-letsencrypt:/etc/letsencrypt


volumes:
    db-data:
        driver: local
    certbot-webroot-le-cerf-vert:
    certbot-letsencrypt: